services:
  server:
    container_name: r3_server
    image: fancescoxx/rustapp:latest
    environment:
      DATABASE_ARGS: ${DATABASE_ARGS}
    build:
      context: ./server
      dockerfile: rust.Dockerfile
      args:
        DATABASE_ARGS: ${DATABASE_ARGS}
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: r3_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 6543:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

volumes:
  pgdata: {}
